### ISSUE TITLE
Preprocessor excluded regions aren't properly rehighlighted after removed

### ISSUE THREAD

**Issue by rgreenblatt** [jackguo380/vim-lsp-cxx-highlight#61] opened 2021-04-19 21:00 UTC
```cpp
#include <iostream>

int main()
{
#ifdef TOTALLY_NOT_DEFINED
  std::cout << "hello world\n";
#endif
  
}
```
If you remove the `ifdef`, then the `<< "hello world\n"` isn't highlighted properly (it remains grey). 

![image](https://user-images.githubusercontent.com/8813096/115302336-5581bc80-a130-11eb-9dd6-b72a28057309.png)

It seems that the corresponding highlight group isn't being removed (or similar).

I am using ccls (official arch package) with clang 11.1, neovim, and coc.nvim.

If this can't be reproduced easily let me know and I will add log files and create a minimal configuration which reproduces this.

**Comment by jackguo380** [comment] 2021-04-25 23:02
Hi greenblatt,

Thanks for reporting this, it was fairly easy to reproduce. I have pushed a fix onto master, could you test it out and see if it fixes your issue?

Thanks.

**Comment by rgreenblatt** [comment] 2021-04-27 03:15
Yep, looks like this is fixed, thanks!

**Comment by jackguo380** [comment] 2021-04-29 19:27
Reopening as ce92c8e9b1ab587eb22ad017d536619b6a100d09 seems to have caused a regression.

The highlighting flashes on saving which is worse than having leftover highlights so I am going to revert this fix for now and come up with a better one.

The cause seems to be that ccls is sending an empty notification immediately after saving and then sending the real highlighting after finishing analyzing (usually 500ms to a few seconds depending on file size).

**Closed** 2021-10-20 05:29 UTC
