### ISSUE TITLE
(coc.nvim + clangd) Semantic highlighting seems to cut off when entering insert mode in NeoVim

### ISSUE THREAD

**Issue by R-Michelsen** [jackguo380/vim-lsp-cxx-highlight#20] opened 2020-04-13 02:14 UTC
**Describe the bug**
Im experiencing some weird behaviour with the highlighting, whenever I enter
insert mode, the semantic highlighting disappears for all text above the cursor.

**To Reproduce**
Open any .cpp file with coc.nvim/clangd + vim-lsp-cxx-highlight.
Observe that semantic highlighting works properly, then enter 
insert mode.

**Screenshots**
![](https://i.imgur.com/v2lqhtD.png)

**Configuration (Fill this out):**
 - Neovim NVIM v0.5.0-372-ge63b25eb2
 - coc.nvim + clangd (10.0.0) Windows 10 binaries

**Log File:**
```vim
4/13/2020 4:14:06 AM: lsp_cxx_hl beginning initialization...
4/13/2020 4:14:06 AM: vim-lsp not detected
4/13/2020 4:14:06 AM: LanguageClient-neovim not detected
4/13/2020 4:14:06 AM: coc.nvim successfully registered
4/13/2020 4:14:06 AM: nvim-lsp successfully registered
4/13/2020 4:14:07 AM: textprop nvim notify symbols for .\AppEditorLogic.cpp
4/13/2020 4:14:07 AM: hl_symbols (textprop nvim) highlighted 18 symbols in file .\AppEditorLogic.cpp
4/13/2020 4:14:07 AM: operation hl_symbols (textprop nvim) .\AppEditorLogic.cpp took   0.002619s to complete
4/13/2020 4:14:10 AM: textprop nvim notify symbols for .\AppEditorLogic.cpp
4/13/2020 4:14:10 AM: hl_symbols (textprop nvim) highlighted 12 symbols in file .\AppEditorLogic.cpp
4/13/2020 4:14:10 AM: operation hl_symbols (textprop nvim) .\AppEditorLogic.cpp took   0.001566s to complete
```

**Comment by jackguo380** [comment] 2020-04-14 03:25
Hi R-Michelsen,

Thanks for reporting this. I just tested out `NVIM v0.5.0-429-g13b4a6fd4` with clangd 11 and am seeing a similar issue. The highlighting will disappear from the buffer after entering insert mode and typing anything.

I suspect the cause is related to my [comment on coc-clangd](https://github.com/clangd/coc-clangd/pull/27#issuecomment-602808843) about incremental highlighting. @fannheyward Maybe having `coc-clangd` cache previous highlighting messages then calling `lsp_cxx_hl#hl#notify_symbols` would fix this issue. What do you think?

For now if you want something that works clangd 9.0.0 shouldn't have this problem as long as you are willing to downgrade to it.

**Comment by sam-mccall** [comment] 2020-04-20 21:25
> Maybe having coc-clangd cache previous highlighting messages then calling lsp_cxx_hl#hl#notify_symbols would fix this issue. What do you think?

Indeed, fixed in https://github.com/clangd/coc-clangd/commit/008da37c06d1068ce207fff840468fe307927092 and it seems to work well.
We need a new release of coc-clangd though, hopefully soon.

**Comment by fannheyward** [comment] 2020-04-21 01:37
coc-clangd has released a new version with this fix.

**Comment by jackguo380** [comment] 2020-04-21 02:36
Just tested it out as well, looks like it is fixed.

Thanks @sam-mccall @fannheyward 

@R-Michelsen if updating to the latest `coc-clangd` fixes it for you please close the issue.

**Closed** 2020-04-28 21:56 UTC
